### ISSUE TITLE
Does this work to script a recursive button press?

### ISSUE THREAD

**Issue by jvhgamer** [deftflux/descent-glovepie#1]
I want to have a script that tells the controller to press the A button, or send the command that it send when manually pressing the A button, every 30 seconds. Is this possible with your script?

**Comment by meyertime** [comment]
This is a program for generating GlovePIE scripts.  What you are asking I believe is possible with GlovePIE, but it would not be within the scope of this script generator.  In other words, you could use GlovePIE and simply write your own script.

However, GlovePIE is basically dead; the author has disappeared and allowed the GlovePIE website to expire.  I would recommend using [FreePIE](http://andersmalmgren.github.io/FreePIE/) instead.  Or, if you're brave, the project I started, [JsPie](https://github.com/deftflux/jspie), which is currently early early alpha and only supports the PS3 controller, but executes actual JavaScript using a real JavaScript engine, which is a bit more powerful.

**Comment by jvhgamer** [comment]
deftflux! thanks for the quick response. i have my xbox one controller plugged into the computer and its synced and working with my one. is there a way to open a controller interface to send buttons presses??

**Comment by meyertime** [comment]
It sounds like you're trying to use a computer to send button presses to an Xbox one console through a controller... I'm afraid it doesn't work like that. I thought you meant simulating button presses to a game running on the computer.

To do what you're asking would probably require some kind of hardware. The easiest way to do it would probably be to cannabalize an Xbox one controller, connecting the button's electrical contacts to an Arduino output (through a relay of course) and programming the Arduino to turn the output on and off to simulate the button presses. (I'm using the word "easiest" loosely...) That is, unless someone has figured out how to communicate with an Xbox one console via Bluetooth or USB and act as a controller without being certified by Microsoft...
